pde_name: "2D_Compressible_NS"
model_name: "DeepONet"
if_training: True
continue_training: False
model_path: "./checkpoint/2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train/2d_CFD_128_ar_lr0.001_bs50-best.pt"
output_dir: "./checkpoint/"
save_period: 10
seed: 0   
initial_step: 10
epochs: 200

model:
  size: 128
  act: 'tanh'
  in_channels : 4   # input
  out_channels : 4   # output
  query_dim: 2
  base_model: "MLP"
train:
  scenario : "2D_Compressible_NS"
  save_name : "2d_CFD_128_ar"
  training_type: "autoregressive"

dataset:
  name : "2D_Compressible_NS"
  single_file: True
  file_name: "2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train.hdf5"
  saved_folder: "/data1/zhouziyang/datasets/pdebench/2D/CFD/2D_Train_Rand/"
  reduced_resolution: 1
  reduced_resolution_t: 1
  reduced_batch: 1
  test_ratio: 0.1
# dataloader相关参数
dataloader:
  batch_size: 50
  num_workers: 2
  pin_memory: True
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay : 1.e-4
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 50
  gamma: 0.5
