pde_name: "2D_shallow_water"
model_name: "DeepONet"
if_training: True
continue_training: False
model_path: "./checkpoint/2D_rdb_NA_NA/2d_SWE_128_ar_lr0.001_bs50-best.pt"
output_dir: "./checkpoint/"
save_period: 10
seed: 0
initial_step: 10
epochs: 200

model:
  size: 128
  act: 'tanh'
  in_channels : 1   # input  : h    (u,v have no data except an initial condition =0 )
  out_channels : 1   # output : h
  query_dim: 2
  base_model: "MLP"
train:
  scenario : "2D_shallow_water"
  save_name : "2d_SWE_128_ar"
  training_type: "autoregressive"   # or single

dataset:
  name : "2D_SWE"
  single_file: False
  file_name: "2D_rdb_NA_NA.h5"
  saved_folder: "/data1/zhouziyang/datasets/pdebench/2D/shallow-water/"
  reduced_resolution: 1
  reduced_resolution_t: 1
  reduced_batch: 1
  test_ratio: 0.1
# dataloader相关参数
dataloader:
  batch_size: 50
  num_workers: 1
  pin_memory: False
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay : 1.e-4
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 50
  gamma: 0.5
