pde_name: "1D_Allen_Cahn"
model_name: "PINO"
if_training: False
continue_training: False
model_path: "./checkpoint/1D_Allen-Cahn_0.0001_5/1d_Allen_Cahn_2x_lr0.001_bs50-best.pt"
output_dir: "./checkpoint/"
save_period: 20
seed: 0
training_type: "single"   
initial_step: 1
epochs: 500

model:
  width : 32
  modes1: [12, 12, 12, 12]
  modes2: [12, 12, 12, 12]
  fc_dim: 128
  act: 'gelu'
  in_channels : 1   # input
  out_channels : 1   # output

train:
  scenario : "1D_Allen_Cahn"
  scheduler_gamma: 0.5
  ic_loss: 5.0
  f_loss: 1.0
  xy_loss: 10.0
  save_name : "1d_Allen_Cahn_2x"


dataset:
  name : "1D_Allen_Cahn"
  single_file: True
  file_name: "1D_Allen-Cahn_0.0001_5.hdf5"
  saved_folder: "/data1/zhouziyang/datasets/pdebench/1D/Allen-Cahn/"
  reduced_resolution: 8
  reduced_resolution_t: 5
  reduced_resolution_pde: 4
  reduced_resolution_pde_t: 5
  reduced_batch: 1
  test_ratio: 0.1
  if_grid_norm : False
# dataloader相关参数
dataloader:
  batch_size: 50
  num_workers: 4
  pin_memory: False
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay : 1.e-4
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5
