# PDE类相关参数
pde_name: "1D_Burgers"
temporal_domain: (0, 2)
resolution_t: 201
spatial_domain: "[(0, 1)]"
resolution: [1024]
variables: {"nu": 0.001}
# 训练相关参数
if_training: False
continue_training: False
model_path: "./checkpoint/1D_Burgers_Sols_Nu0.001/MPNN_lr0.0001_bs16-best.pt"
output_dir: "./checkpoint/"
save_period: 2
seed: 0
time_window: 10
neighbors: 3 # create graph
unrolling: 1
epochs: 20
# 数据集相关参数
dataset:
  single_file: True
  file_name: "1D_Burgers_Sols_Nu0.001.hdf5"
  saved_folder: "/data1/zhouziyang/datasets/pdebench/1D/Burgers/Train/"
  reduced_resolution: 4
  reduced_resolution_t: 5
  reduced_batch: 1
  test_ratio: 0.1
# dataloader相关参数
dataloader:
  batch_size: 16
  num_workers: 2
  pin_memory: True
# 模型相关参数
model_name: "MPNN"
model:
  hidden_features: 128
  hidden_layer: 6
# 优化器相关参数
optimizer:
  name: 'AdamW'
  lr: 1.e-4
# scheduler相关参数
scheduler:
  name: "MultiStepLR"
  milestones: [1, 5, 10, 15]
  gamma: 0.4