pde_name: "2D_convection-diffusion"
model_name: "UNO"
if_training: False
continue_training: False
model_path: "./checkpoint/Convection_diffusion/Convection_diffusion_FNO-best.pt"
output_dir: "./checkpoint/"
save_period: 20
# 训练相关参数
seed: 0
training_type: "autoregressive"
pushforward: True
t_train: 101
initial_step: 10
unroll_step: 20
epochs: 500
# 数据集相关参数 
dataset:
  single_file: True
  file_name: "Convection_diffusion.hdf5"
  saved_folder: "/data1/zhouziyang/datasets/pdebench/2D/Convection_diffusion/"
  reduced_resolution: 1
  reduced_resolution_t: 1
  reduced_batch: 1
# dataloader相关参数
dataloader:
  batch_size: 8
  num_workers: 2
  pin_memory: False
# 模型相关参数
model:
  num_channels: 1
  width: 16
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5