pde_name: "1D_diffusion_sorption"
model_name: "UNet"
if_training: False
continue_training: False
model_path: "./checkpoint2/1D_diff-sorp_NA_NA/UNet_lr0.001_bs64_PF20-best.pt"
output_dir: "./checkpoint2/"
save_period: 20
# 训练相关参数
seed: 0
training_type: "autoregressive"
pushforward: True
t_train: 101
initial_step: 10
unroll_step: 20
epochs: 500
# 数据集相关参数
dataset:
  single_file: False
  file_name: "1D_diff-sorp_NA_NA.h5"
  saved_folder: "/data1/zhouziyang/datasets/pdebench/1D/diffusion-sorption/"
  reduced_resolution: 4
  reduced_resolution_t: 1
  reduced_batch: 1
  test_ratio: 0.1
# dataloader相关参数
dataloader:
  batch_size: 64
  num_workers: 4
  pin_memory: False
# 模型相关参数
model:
  in_channels: 1
  out_channels: 1
  init_features: 32
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5