pde_name: "2D_Darcy_Flow"
model_name: "UNet"
if_training: True
continue_training: False
model_path: null
output_dir: "./checkpoint1/"
save_period: 10
# 训练相关参数
seed: 0
training_type: "single"
pushforward: False
t_train: 2
initial_step: 1
unroll_step: 1
epochs: 10
# 数据集相关参数
dataset:
  single_file: True
  file_name: "2D_DarcyFlow_beta1.0_Train.hdf5"
  saved_folder: "/data1/zhouziyang/datasets/pdebench/2D/DarcyFlow/"
  reduced_resolution: 1
  reduced_resolution_t: 1
  reduced_batch: 1
  test_ratio: 0.1
# dataloader相关参数
dataloader:
  batch_size: 64
  num_workers: 4
  pin_memory: True
# 模型相关参数
model:
  in_channels: 1
  out_channels: 1
  init_features: 32
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5