model_name: 'DFVM'
scenario: 'pde1D'
seed: 0000
model_update: 500
filename: 'ReacDiff_Nu0.5_Rho1.0.hdf5'
epochs: 15000
input_ch: 2
output_ch: 1
learning_rate: 1.e-3
root_path: '/home/data2/fluidbench/1D/ReactionDiffusion/'
val_num: 1
if_periodic_bc: True
period: 5000
val_time: 2.0
val_batch_idx: -1
aux_params: [0.5, 1.0]
vol_size: 1
vol_ep: 1.e-4