pde_name: "2D_Compressible_NS"
model_name: "FNO"
if_training: False
continue_training: False
model_path: "./checkpoint/2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train/2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train_FNO-best.pt"
output_dir: "./checkpoint/"
save_period: 20
# 训练相关参数
seed: 0
training_type: "autoregressive"
pushforward: True
t_train: 21
initial_step: 10
unroll_step: 20
epochs: 500
# 数据集相关参数 
dataset:
  single_file: True
  file_name: "2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train.hdf5"
  saved_folder: "/data1/zhouziyang/datasets/pdebench/2D/CFD/2D_Train_Rand/"
  reduced_resolution: 1
  reduced_resolution_t: 1
  reduced_batch: 1
# dataloader相关参数
dataloader:
  batch_size: 32
  num_workers: 4
  pin_memory: True
# 模型相关参数
model:
  num_channels: 4
  modes: 12
  width: 20
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5