pde_name: "2D_Burgers"
model_name: "FNO"
if_training: True
continue_training: False
model_path: null
output_dir: "./checkpoint/"
save_period: 20
# 训练相关参数
seed: 0
training_type: "autoregressive"
pushforward: True
t_train: 101
initial_step: 10
unroll_step: 20
epochs: 500
# 数据集相关参数 
dataset:
  single_file: False
  file_name: "2D_Burgers_Nu0.001.hdf5"
  saved_folder: "/data1/zhouziyang/datasets/pdebench/2D/Burgers/"
  reduced_resolution: 1
  reduced_resolution_t: 1
  reduced_batch: 1
# dataloader相关参数
dataloader:
  batch_size: 8
  num_workers: 2
  pin_memory: False
# 模型相关参数
model:
  num_channels: 2
  modes: 12
  width: 20
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5