pde_name: "2D_Darcy_Flow"
model_name: "FNO"
if_training: False
continue_training: False
model_path: "./checkpoint/2D_DarcyFlow_beta1.0_Train/2D_DarcyFlow_beta1.0_Train_FNO-best.pt"
output_dir: "./checkpoint/"
save_period: 20
# 训练相关参数
seed: 0
training_type: "single"
pushforward: False
t_train: 2
initial_step: 1
unroll_step: 1
epochs: 500
# 数据集相关参数 
dataset:
  single_file: True
  file_name: "2D_DarcyFlow_beta1.0_Train.hdf5"
  saved_folder: "/data1/zhouziyang/datasets/pdebench/2D/DarcyFlow/"
  reduced_resolution: 1
  reduced_resolution_t: 1
  reduced_batch: 1
# dataloader相关参数
dataloader:
  batch_size: 64
  num_workers: 4
  pin_memory: False
# 模型相关参数
model:
  num_channels: 1
  modes: 12
  width: 20
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5