pde_name: "1D_diffusion_sorption"
model_name: "FNO"
if_training: False
continue_training: False
model_path: "./checkpoint/1D_diff-sorp_NA_NA/1D_diff-sorp_NA_NA.h5_FNO-best.pt"
output_dir: "./checkpoint/"
save_period: 20
# 训练相关参数
seed: 0
training_type: "autoregressive"
pushforward: True
t_train: 101
initial_step: 10
unroll_step: 20
epochs: 500
# 数据集相关参数 
dataset:
  single_file: False
  file_name: '1D_diff-sorp_NA_NA.h5'
  saved_folder: "/home/zhouziyang/lihj/PDEBench/pdebench/data/1D/diffusion-sorption/"
  reduced_resolution: 1
  reduced_resolution_t: 1
  reduced_batch: 1
# dataloader相关参数
dataloader:
  batch_size: 64
  num_workers: 4
  pin_memory: False
# 模型相关参数
model:
  num_channels: 1
  modes: 12
  width: 20
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5