model_name: 'PINN'
scenario: 'CFD2D'
model_update: 500
filename: '2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train.hdf5'
epochs: 15000
input_ch: 3
output_ch: 4
learning_rate: 1.e-3
root_path: '/data1/zhouziyang/datasets/pdebench/2D/CFD/2D_Train_Rand/'
val_num: 2
if_periodic_bc: True
period: 5000
val_time: 1.0
val_batch_idx: 10
aux_params: [1.6666666667]
seed: '0000'