model_name: 'PINN'
scenario: 'pde1D'
model_update: 500
filename: '1D_Allen-Cahn_0.0001_5.hdf5'
epochs: 15000
input_ch: 2
output_ch: 1
learning_rate: 1.e-3
root_path: '/data1/zhouziyang/datasets/pdebench/1D/Allen-Cahn/'
val_num: 2
if_periodic_bc: True
period: 5000
val_time: 1.0
val_batch_idx: 10
aux_params: [0.0001, 5.0]
seed: '0000'