pde_name: "1D_compressible_NS"
model_name: "DeepONet"
if_training: False
continue_training: True
model_path: "./checkpoint/1D_CFD_Rand_Eta0.1_Zeta0.1_periodic_Train/1d_CFD_lr0.001_bs50-latest.pt"
output_dir: "./checkpoint/"
save_period: 20
seed: 1
training_type: "autoregressive"   
initial_step: 10
epochs: 500

model:
  act: 'tanh'
  in_channels : 3   # input
  out_channels : 3   # output

train:
  scenario : "1D_compressible_NS"
  save_name : "1d_CFD"


dataset:
  name : "1D_compressible_NS"
  single_file: True
  file_name: "1D_CFD_Rand_Eta0.1_Zeta0.1_periodic_Train.hdf5"
  saved_folder: "/data1/zhouziyang/datasets/pdebench/1D/CFD/Train/"
  reduced_resolution: 4
  reduced_resolution_t: 1
  reduced_batch: 1
  test_ratio: 0.1
# dataloader相关参数
dataloader:
  batch_size: 50
  num_workers: 1
  pin_memory: False
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay : 1.e-4
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5