pde_name: "1D_Burgers"
model_name: "DeepONet"
if_training: False
continue_training: False
model_path: "./checkpoint/1D_Burgers_Sols_Nu0.001/1d_burgers_256_41_lr0.001_bs50-best.pt"          # path of checkpoint
output_dir: "./checkpoint/"
save_period: 20
training_type: "autoregressive"    
initial_step: 10           
epochs: 500
seed : 0

model:
  act: 'tanh'
  in_channels : 1   # input
  out_channels : 1   # output

train:
  scenario : "1D_Burgers"
  save_name : "1d_burgers_256_41"

################################################################

dataset:
  name : "Burgers"
  single_file: True
  file_name: "1D_Burgers_Sols_Nu0.001.hdf5"
  saved_folder: "/data1/zhouziyang/datasets/pdebench/1D/Burgers/Train/"
  reduced_resolution: 4 
  reduced_resolution_t: 5
  reduced_batch: 1
  test_ratio: 0.1
# dataloader相关参数
dataloader:
  batch_size: 50
  num_workers: 1
  pin_memory: False
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay : 1.e-4
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5
