pde_name: "1D_Cahn_Hilliard"
model_name: "DeepONet"
if_training: False
continue_training: False
model_path: "./checkpoint/1D_Cahn-Hilliard_10e-6_0.01/1d_Cahn_Hilliard_lr0.001_bs50-best.pt"
output_dir: "./checkpoint/"
save_period: 20
seed: 0
training_type: "autoregressive"   
initial_step: 10
epochs: 500

model:
  act: 'tanh'
  in_channels : 1   # input
  out_channels : 1   # output

train:
  scenario : "1D_Cahn_Hilliard"
  save_name : "1d_Cahn_Hilliard"


dataset:
  name : "1D_Cahn_Hilliard"
  single_file: True
  file_name: "1D_Cahn-Hilliard_10e-6_0.01.hdf5"
  saved_folder: "/data1/zhouziyang/datasets/pdebench/1D/Cahn-Hilliard/"
  reduced_resolution: 4
  reduced_resolution_t: 5
  reduced_batch: 1
  test_ratio: 0.1
# dataloader相关参数
dataloader:
  batch_size: 50
  num_workers: 4
  pin_memory: False
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay : 1.e-4
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5