pde_name: "2D_DarcyFlow"
model_name: "DeepONet"
if_training: False
continue_training: False
model_path: "./checkpoint/2D_DarcyFlow_beta1.0_Train/2d_darcy_128_lr0.001_bs50-best.pt"
output_dir: "./checkpoint/"
save_period: 20
seed: 0
training_type: "autoregressive"   
initial_step: 1
epochs: 500

model:
  act: 'tanh'
  in_channels : 1   # input
  out_channels : 1   # output

train:
  scenario : "2D_DarcyFlow"
  save_name : "2d_darcy_128"


dataset:
  name : "2D_DarcyFlow"
  single_file: True
  file_name: "2D_DarcyFlow_beta1.0_Train.hdf5"
  saved_folder: "/data1/zhouziyang/datasets/pdebench/2D/DarcyFlow/"
  reduced_resolution: 1
  reduced_resolution_t: 1
  reduced_batch: 1
  test_ratio: 0.1
# dataloader相关参数
dataloader:
  batch_size: 50
  num_workers: 2
  pin_memory: False
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay : 1.e-4
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5